on:
  schedule:
    - cron: 0 0 1 * * # run monthly
  workflow_dispatch:

name: Broken Link Check
jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Broken Link Check
        uses: technote-space/broken-link-checker-action@v2
        with:
          TARGET: |
            - https://www.zaproxy.org/evangelists/
            - https://www.zaproxy.org/student-hall-of-fame/
            - kingthorin.github.io/test/
            - https://owasp.org/www-community/fail
          RECURSIVE: false
